services:
  web:
    image: ts-custom-dc-website-compose
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: build/web_compose/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.list
    environment:
      - DEBUG=true
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
      - ./tmp/custom_dc/import_data:/userdata
      - ./server:/workspace/server
      - ./static:/workspace/static
      - ./import:/workspace/import
      - $HOME/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro