services:
  web:
    platform: "linux/amd64"
#    image: gcr.io/datcom-ci/datacommons-services:stable
    image: ts-custom-cdc-services
    build:
      context: .
      dockerfile: build/cdc_services/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.list
    environment:
      - DOCKER_BUILDKIT=1
      - DEBUG=true
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
      - ./tmp/custom_dc:/userdata
      - ./server/templates:/server/templates